"""user professions

Revision ID: db2e46cfa659
Revises: f5f71a987b95
Create Date: 2019-10-11 01:44:13.452795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2e46cfa659'
down_revision = 'f5f71a987b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profession_one', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('profession_two', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profession_two')
    op.drop_column('user', 'profession_one')
    # ### end Alembic commands ###
